object Modules {
    const val Framework = ":libraries:framework"
    const val Testing = ":libraries:testing"
    const val Theme = ":common:ui-theme"
    const val Resource = ":common:ui-resource"
    const val View = ":common:ui-view"
    const val Model = ":data:model"
    const val Remote = ":data:remote"
    const val Local = ":data:local"
    const val Repository = ":data:repository"
    const val Domain = ":domain"
    const val Splash = ":features:splash"
    const val Characters = ":features:characters"
    const val Detail = ":features:detail"
    const val Favorites = ":features:favorites"
    const val Settings = ":features:settings"
    const val Main = ":features:main"
    const val Home = ":features:home"
    const val Provider = ":common:provider"
}
